# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08fe18c2a979bff8c4167f7c5b387e4aa994d05e0aa1bf78e9a39a140ffffb08e7ba2faedcfebebfe2b16556f84d2877b984628882bb089c573d1b06e31c4f4d

test:
  secret_key_base: 5032311aa8c595201a9b9cf9978fd3113652df34a86bda901d8901b2ff8a7fb7ad36b363796206a74882abe76c25a51b80adfaa7ce321c63b23b0c2f46de9332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
